ENV["GKSwstype"] = get(ENV, "GKSwstype", "100")

using JLD2
using PlotlyJS
using Printf
using SHA
using Statistics

include(joinpath(@__DIR__, "Package6Analysis.jl"))
include(joinpath(@__DIR__, "Package6Study.jl"))
using .Package6Analysis
using .Package6Study

const PROTOCOLS = (:fixed, :varying)
const PROTOCOL_NAMES = Dict(:fixed => "Fixed IC", :varying => "Varying IC")
const QUALITY_THRESHOLDS = P6_QUALITY_THRESHOLDS
const QUALITY_TARGETS = (12, 6, 3, 2)
const HITTING_TARGETS = (48, 24, 12, 6, 3, 1)
const CONTROLLER_ORDER = ("expert", "C_match", "C_sparse")
const CONTROLLER_NAMES = Dict("expert" => "Expert", "C_match" => "C_match", "C_sparse" => "C_sparse")

# The method colors deliberately reuse two colors from the MAT-stability study.
const GO_COLOR = "#277DA1"
const GR_COLOR = "#F2A13A"
const THIRD_COLOR = "#B41A5C"
const NEUTRAL_COLOR = "#4D4D4D"
const GRID_COLOR = "#E6E6E6"
const STRENGTH_COLORS = ("#2166AC", "#4393C3", "#92C5DE", "#D6604D", "#B2182B")
# Reuse the four-color threshold palette selected from the GO-strength
# calibration and add the earlier packages' yellow-orange for strength five.
const EVALUATION_STRENGTH_COLORS = ("#2166AC", "#92C5DE", "#D6604D", "#67001F", GR_COLOR)
const REPLICATE_COLORS = (GO_COLOR, GR_COLOR, THIRD_COLOR)
const RESET_COLORS = Dict(:group => GO_COLOR, :mse => GR_COLOR, :joint => THIRD_COLOR)
const RESET_LABELS = Dict(:group => "Group reset", :mse => "MSE reset", :joint => "Joint reset")
const CONTROLLER_COLORS = Dict("expert" => NEUTRAL_COLOR, "C_match" => GO_COLOR, "C_sparse" => GR_COLOR)

function usage(io::IO = stdout)
    println(io, """
    Usage:
      julia --startup-file=no --project=. Revision/GO_Sensitivity/make_paper_figures.jl [options]

    Options:
      --results-dir DIR  Package-6 study root (default: Revision/GO_Sensitivity/results/study).
      --output-dir DIR   Output directory (default: <results-dir>/paper).
      --check-only       Validate inputs and calculate metrics without exporting figures.
      --self-test        Run deterministic tests that require no study results.
      --help             Show this message.

    The script consumes the fixed and varying analysis products generated by
    analyze_study_worker.jl. It never starts training, validation, or test rollouts.
    """)
end

function parse_arguments(arguments)
    values = Dict{String, Any}(
        "results_dir" => joinpath(@__DIR__, "results", "study"),
        "output_dir" => nothing,
        "check_only" => false,
        "self_test" => false,
    )
    index = 1
    while index <= length(arguments)
        argument = arguments[index]
        if argument == "--help"
            usage()
            return nothing
        elseif argument == "--check-only"
            values["check_only"] = true
            index += 1
        elseif argument == "--self-test"
            values["self_test"] = true
            index += 1
        elseif argument in ("--results-dir", "--output-dir")
            index < length(arguments) || error("Missing value after $argument.")
            values[replace(argument[3:end], '-' => '_')] = arguments[index + 1]
            index += 2
        else
            error("Unknown argument '$argument'. Use --help for usage.")
        end
    end
    results_dir = abspath(string(values["results_dir"]))
    output_dir = isnothing(values["output_dir"]) ? joinpath(results_dir, "paper") : abspath(string(values["output_dir"]))
    return (;
        results_dir,
        output_dir,
        check_only = Bool(values["check_only"]),
        self_test = Bool(values["self_test"]),
    )
end

function split_csv_line(line::AbstractString)
    fields = String[]
    buffer = IOBuffer()
    quoted = false
    index = firstindex(line)
    while index <= lastindex(line)
        character = line[index]
        if character == '"'
            next_index = nextind(line, index)
            if quoted && next_index <= lastindex(line) && line[next_index] == '"'
                write(buffer, '"')
                index = nextind(line, next_index)
                continue
            end
            quoted = !quoted
        elseif character == ',' && !quoted
            push!(fields, String(take!(buffer)))
        else
            write(buffer, character)
        end
        index = nextind(line, index)
    end
    quoted && error("Unterminated quoted CSV field.")
    push!(fields, String(take!(buffer)))
    return fields
end

function read_csv(path::AbstractString)
    isfile(path) || error("Required CSV is missing: $path")
    lines = readlines(path)
    isempty(lines) && error("CSV is empty: $path")
    headers = Symbol.(split_csv_line(chomp(lines[1])))
    rows = Dict{Symbol, String}[]
    for (offset, line) in enumerate(lines[2:end])
        line_number = offset + 1
        isempty(strip(line)) && continue
        values = split_csv_line(chomp(line))
        length(values) == length(headers) || error("CSV column mismatch in $path at line $line_number.")
        push!(rows, Dict(headers[index] => values[index] for index in eachindex(headers)))
    end
    return rows
end

string_value(row, key::Symbol) = row[key]
int_value(row, key::Symbol) = parse(Int, row[key])
float_value(row, key::Symbol) = parse(Float64, row[key])
symbol_value(row, key::Symbol) = Symbol(row[key])

function optional_float(row, key::Symbol)
    value = strip(row[key])
    isempty(value) && return missing
    return parse(Float64, value)
end

function csv_escape(value)
    value === missing && return ""
    text = string(value)
    occursin(r"[\",\n\r]", text) || return text
    return "\"" * replace(text, "\"" => "\"\"") * "\""
end

function write_csv(path, rows)
    rows = collect(rows)
    mkpath(dirname(path))
    keys_order = isempty(rows) ? Symbol[] : sort!(unique(vcat([collect(keys(row)) for row in rows]...)); by = string)
    open(path, "w") do io
        println(io, join(string.(keys_order), ','))
        for row in rows
            println(io, join((csv_escape(haskey(row, key) ? row[key] : missing) for key in keys_order), ','))
        end
    end
    return path
end

function required_paths(results_dir, protocol)
    analysis = joinpath(results_dir, string(protocol), "analysis")
    csv = joinpath(analysis, "csv")
    test = joinpath(analysis, "test")
    return Dict(
        :status => joinpath(analysis, "status.jld2"),
        :candidates => joinpath(analysis, "candidate_manifest.jld2"),
        :checkpoints => joinpath(csv, "checkpoint_metrics.csv"),
        :fronts => joinpath(csv, "front_points.csv"),
        :attainment => joinpath(csv, "global_attainment.csv"),
        :hitting => joinpath(csv, "hitting_summary.csv"),
        :resets => joinpath(csv, "reset_summary.csv"),
        :archive => joinpath(csv, "archive_convergence.csv"),
        :test_episodes => joinpath(test, "test_episodes.csv"),
        :test_returns => joinpath(test, "test_returns.csv"),
    )
end

function validate_status(path, protocol)
    isfile(path) || error("Analysis status is missing: $path")
    loaded = JLD2.load(path)
    Symbol(loaded["state"]) === :complete || error("$(PROTOCOL_NAMES[protocol]) analysis is not complete.")
    Symbol(loaded["protocol"]) === protocol || error("Protocol mismatch in $path.")
    Int(loaded["training_run_count"]) == 18 || error("Expected 18 training runs in $path.")
    return loaded
end

function load_candidates(path, protocol)
    isfile(path) || error("Candidate manifest is missing: $path")
    loaded = JLD2.load(path)
    Symbol(loaded["protocol"]) === protocol || error("Candidate protocol mismatch in $path.")
    loaded["selection_uses_test_data"] == false || error("Candidate selection unexpectedly used test data.")
    loaded["frozen_before_test"] == true || error("Candidate manifest was not frozen before testing.")
    candidates = Dict{String, Dict{Symbol, Any}}()
    for raw in loaded["candidates"]
        candidate = Dict{Symbol, Any}(Symbol(key) => value for (key, value) in raw)
        candidates[string(candidate[:selection_role])] = candidate
    end
    haskey(candidates, "C_match") || error("$protocol has no C_match candidate.")
    return candidates
end

function load_protocol(results_dir, protocol)
    paths = required_paths(results_dir, protocol)
    for path in values(paths)
        isfile(path) || error("Required Package-6 artifact is missing: $path")
    end
    status = validate_status(paths[:status], protocol)
    candidates = load_candidates(paths[:candidates], protocol)
    return (;
        protocol,
        paths,
        status,
        candidates,
        checkpoints = read_csv(paths[:checkpoints]),
        fronts = read_csv(paths[:fronts]),
        attainment = read_csv(paths[:attainment]),
        hitting = read_csv(paths[:hitting]),
        resets = read_csv(paths[:resets]),
        archive = read_csv(paths[:archive]),
        test_episodes = read_csv(paths[:test_episodes]),
        test_returns = read_csv(paths[:test_returns]),
    )
end

function validate_loaded_data(data)
    go_runs = unique(string_value(row, :run_id) for row in data.checkpoints if string_value(row, :method) == "go")
    gr_runs = unique(string_value(row, :run_id) for row in data.checkpoints if string_value(row, :method) == "gr")
    length(go_runs) == 15 || error("$(data.protocol): expected 15 GO runs, found $(length(go_runs)).")
    length(gr_runs) == 3 || error("$(data.protocol): expected 3 GR runs, found $(length(gr_runs)).")
    strengths = sort(unique(float_value(row, :regularization_strength) for row in data.checkpoints if string_value(row, :method) == "go"))
    strengths == sort(collect(P6_STRENGTHS[data.protocol])) || error("$(data.protocol): GO strength grid differs from Package6Study.jl.")
    roles = Set(string_value(row, :role) for row in data.test_episodes)
    "expert" in roles || error("$(data.protocol): expert test episodes are missing.")
    "C_match" in roles || error("$(data.protocol): C_match test episodes are missing.")
    all(haskey(row, :global_nusselt) for row in data.test_episodes) || error("$(data.protocol): state_Nu test values are missing.")
    return nothing
end

function response_metrics(data)
    threshold = QUALITY_THRESHOLDS[data.protocol]
    rows = NamedTuple[]
    for replicate in P6_REPLICATES, (strength_index, strength) in enumerate(P6_STRENGTHS[data.protocol])
        matching = [row for row in data.fronts if
            string_value(row, :front_scope) == "run" &&
            string_value(row, :method) == "go" &&
            int_value(row, :replicate) == replicate &&
            int_value(row, :strength_index) == strength_index &&
            float_value(row, :validation_matching) <= threshold]
        if isempty(matching)
            push!(rows, (;
                protocol = data.protocol, replicate, strength_index,
                strength = Float64(strength), threshold, reached = false,
                active_groups = missing, validation_mse = missing, update = missing,
            ))
        else
            best = first(sort(matching; by = row -> (
                int_value(row, :active_groups),
                float_value(row, :validation_matching),
                int_value(row, :update),
                string_value(row, :run_id),
            )))
            push!(rows, (;
                protocol = data.protocol, replicate, strength_index,
                strength = Float64(strength), threshold, reached = true,
                active_groups = int_value(best, :active_groups),
                validation_mse = float_value(best, :validation_matching),
                update = int_value(best, :update),
            ))
        end
    end
    trends = NamedTuple[]
    for replicate in P6_REPLICATES
        selected = sort(filter(row -> row.replicate == replicate && row.reached, rows); by = row -> row.strength)
        rho = spearman_correlation([row.strength for row in selected], [row.active_groups for row in selected])
        push!(trends, (;
            protocol = data.protocol, replicate, threshold,
            qualified_strengths = length(selected), spearman_rho = rho,
        ))
    end
    return (; rows, trends)
end

function quality_hitting_metrics(data)
    threshold = QUALITY_THRESHOLDS[data.protocol]
    budget = P6_UPDATES[data.protocol]
    run_rows = NamedTuple[]
    for replicate in P6_REPLICATES, (strength_index, strength) in enumerate(P6_STRENGTHS[data.protocol]), target in QUALITY_TARGETS
        matching = [row for row in data.checkpoints if
            string_value(row, :method) == "go" &&
            int_value(row, :replicate) == replicate &&
            int_value(row, :strength_index) == strength_index &&
            int_value(row, :active_groups) <= target &&
            float_value(row, :validation_matching) <= threshold]
        if isempty(matching)
            push!(run_rows, (;
                protocol = data.protocol, replicate, strength_index,
                strength = Float64(strength), target_groups = target, threshold,
                reached = false, first_update = missing, normalized_first_update = missing,
                validation_mse_at_hit = missing,
            ))
        else
            hit = first(sort(matching; by = row -> int_value(row, :update)))
            update = int_value(hit, :update)
            push!(run_rows, (;
                protocol = data.protocol, replicate, strength_index,
                strength = Float64(strength), target_groups = target, threshold,
                reached = true, first_update = update, normalized_first_update = update / budget,
                validation_mse_at_hit = float_value(hit, :validation_matching),
            ))
        end
    end
    summary_rows = NamedTuple[]
    for (strength_index, strength) in enumerate(P6_STRENGTHS[data.protocol]), target in QUALITY_TARGETS
        selected = filter(row -> row.strength_index == strength_index && row.target_groups == target, run_rows)
        reached = filter(row -> row.reached, selected)
        normalized = Float64[row.normalized_first_update for row in reached]
        push!(summary_rows, (;
            protocol = data.protocol, strength_index, strength = Float64(strength),
            target_groups = target, threshold,
            reached_seeds = length(reached), seed_count = length(selected),
            reachability_rate = length(reached) / length(selected),
            median_normalized_first_update = isempty(normalized) ? missing : median(normalized),
            minimum_normalized_first_update = isempty(normalized) ? missing : minimum(normalized),
            maximum_normalized_first_update = isempty(normalized) ? missing : maximum(normalized),
        ))
    end
    return (; run_rows, summary_rows)
end

function attainment_metrics(data)
    rows = NamedTuple[]
    for method in ("go", "gr"), target in QUALITY_TARGETS
        values = Dict{Int, Float64}()
        for required in 1:3
            matching = [row for row in data.attainment if
                string_value(row, :method) == method &&
                int_value(row, :active_groups) == target &&
                int_value(row, :attained_seeds) == required]
            length(matching) == 1 || error("Missing $method attainment at B=$target for $(data.protocol).")
            values[required] = float_value(only(matching), :validation_mse)
        end
        delta = isfinite(values[1]) && isfinite(values[3]) ? log(values[3] / values[1]) : Inf
        push!(rows, (;
            protocol = data.protocol, method, target_groups = target,
            mse_1_of_3 = values[1], mse_2_of_3 = values[2], mse_3_of_3 = values[3],
            log_attainment_spread = delta,
        ))
    end
    return rows
end

function normalized_front_rows(data, method)
    return [Dict{Symbol, Any}(
        :active_groups => int_value(row, :active_groups),
        :validation_matching => float_value(row, :validation_matching),
        :update => int_value(row, :update),
        :run_id => string_value(row, :run_id),
        :candidate_id => string_value(row, :candidate_id),
        :method => Symbol(method),
        :numeric_status => :ok,
    ) for row in data.fronts if
        string_value(row, :front_scope) == "global_method" &&
        string_value(row, :method) == method]
end

function combined_retention_metrics(data)
    go = normalized_front_rows(data, "go")
    gr = normalized_front_rows(data, "gr")
    combined = scientific_front(vcat(go, gr))
    retained = Set(string(record[:candidate_id]) for record in combined)
    return (;
        protocol = data.protocol,
        go_front_points = length(go),
        go_retained = count(record -> string(record[:candidate_id]) in retained, go),
        gr_front_points = length(gr),
        gr_retained = count(record -> string(record[:candidate_id]) in retained, gr),
        combined_front_points = length(combined),
    )
end

function terminal_metrics(data)
    rows = NamedTuple[]
    for role in CONTROLLER_ORDER
        selected = filter(row -> string_value(row, :role) == role, data.test_episodes)
        isempty(selected) && continue
        nusselt = float_value.(selected, Ref(:global_nusselt))
        cases = unique(string_value(row, :case) for row in selected)
        per_case_nu = Float64[]
        for case in cases
            case_nusselt = [float_value(row, :global_nusselt) for row in selected if string_value(row, :case) == case]
            push!(per_case_nu, mean(case_nusselt))
        end
        returns = [float_value(row, :return) for row in data.test_returns if string_value(row, :role) == role]
        push!(rows, (;
            protocol = data.protocol, role, cases = length(cases),
            mean_nu = mean(nusselt), median_case_nu = median(per_case_nu),
            minimum_case_nu = minimum(per_case_nu), maximum_case_nu = maximum(per_case_nu),
            mean_200_step_return = mean(returns),
        ))
    end
    return rows
end

function calculate_metrics(data_by_protocol)
    responses = Dict(protocol => response_metrics(data_by_protocol[protocol]) for protocol in PROTOCOLS)
    quality_hitting = Dict(protocol => quality_hitting_metrics(data_by_protocol[protocol]) for protocol in PROTOCOLS)
    attainment = reduce(vcat, [attainment_metrics(data_by_protocol[protocol]) for protocol in PROTOCOLS])
    retention = [combined_retention_metrics(data_by_protocol[protocol]) for protocol in PROTOCOLS]
    terminal = reduce(vcat, [terminal_metrics(data_by_protocol[protocol]) for protocol in PROTOCOLS])
    return (; responses, quality_hitting, attainment, retention, terminal)
end

function rgba(hex::AbstractString, alpha::Real)
    value = replace(hex, "#" => "")
    length(value) == 6 || error("Expected six-digit hex color, got $hex.")
    red = parse(Int, value[1:2]; base = 16)
    green = parse(Int, value[3:4]; base = 16)
    blue = parse(Int, value[5:6]; base = 16)
    return "rgba($red,$green,$blue,$alpha)"
end

function paper_axis(title; log = false, reversed = false, range = nothing, kwargs...)
    fields = Dict{Symbol, Any}(
        :title => attr(text = title, standoff = 10),
        :showline => true,
        :mirror => true,
        :linecolor => "#3A3A3A",
        :linewidth => 1,
        :ticks => "outside",
        :gridcolor => GRID_COLOR,
        :zeroline => false,
        :type => log ? "log" : "linear",
    )
    reversed && (fields[:autorange] = "reversed")
    !isnothing(range) && (fields[:range] = range)
    for (key, value) in kwargs
        fields[key] = value
    end
    return attr(; fields...)
end

function common_layout(; width, height, title, showlegend = true)
    return Layout(
        template = "plotly_white",
        width = width,
        height = height,
        title = attr(text = title, x = 0.5, xanchor = "center", font = attr(size = 22, color = "#252525")),
        paper_bgcolor = "white",
        plot_bgcolor = "white",
        font = attr(family = "Arial, sans-serif", size = 14, color = "#303030"),
        margin = attr(l = 85, r = 35, t = 105, b = 75),
        showlegend = showlegend,
        legend = row_legend(-0.10),
    )
end

function row_legend(y)
    return attr(
        orientation = "h", x = 0.5, xanchor = "center", y = y, yanchor = "top",
        bgcolor = "rgba(255,255,255,0.92)", bordercolor = "#CFCFCF", borderwidth = 1,
        font = attr(size = 12),
    )
end

function preserved_subplot_axis(plot_handle, key::Symbol, styling)
    existing = get(plot_handle.plot.layout.fields, key, Dict{Any, Any}())
    fields = Dict{Symbol, Any}(Symbol(name) => value for (name, value) in existing)
    merge!(fields, styling.fields)
    return attr(; fields...)
end

function add_attainment_band!(plot_handle, data, method, row, col; showlegend, legend_id = "legend")
    color = method == "go" ? GO_COLOR : GR_COLOR
    display = uppercase(method)
    by_required = Dict(required => Dict(
        int_value(item, :active_groups) => float_value(item, :validation_mse)
        for item in data.attainment
        if string_value(item, :method) == method && int_value(item, :attained_seeds) == required
    ) for required in 1:3)
    shared = sort([groups for groups in intersect(keys(by_required[1]), keys(by_required[3]))
                   if isfinite(by_required[1][groups]) && isfinite(by_required[3][groups])])
    if !isempty(shared)
        add_trace!(plot_handle, scatter(
            x = shared, y = [by_required[1][groups] for groups in shared], mode = "lines",
            line = attr(color = rgba(color, 0.45), width = 0.8), hoverinfo = "skip",
            showlegend = false, legendgroup = "$(method)_attainment", legend = legend_id,
        ); row, col)
        add_trace!(plot_handle, scatter(
            x = shared, y = [by_required[3][groups] for groups in shared], mode = "lines",
            line = attr(color = rgba(color, 0.45), width = 0.8), fill = "tonexty",
            fillcolor = rgba(color, 0.12), name = "$display attainment 1/3-3/3",
            showlegend = showlegend, legendgroup = "$(method)_attainment", legend = legend_id,
        ); row, col)
    end
    majority = sort([(groups, value) for (groups, value) in by_required[2] if isfinite(value)]; by = first)
    if !isempty(majority)
        add_trace!(plot_handle, scatter(
            x = first.(majority), y = last.(majority), mode = "lines",
            line = attr(color = color, width = 1.6, dash = "dot"),
            name = "$display attainment 2/3", showlegend = showlegend,
            legendgroup = "$(method)_attainment_majority", legend = legend_id,
        ); row, col)
    end
end

function add_pareto_panel!(plot_handle, data, row, col; showlegend, legend_id = "legend")
    run_ids = sort(unique(string_value(item, :front_id) for item in data.fronts if string_value(item, :front_scope) == "run"))
    for run_id in run_ids
        selected = sort([item for item in data.fronts if string_value(item, :front_scope) == "run" && string_value(item, :front_id) == run_id]; by = item -> int_value(item, :active_groups))
        method = isempty(selected) ? "" : string_value(first(selected), :method)
        isempty(selected) && continue
        add_trace!(plot_handle, scatter(
            x = [int_value(item, :active_groups) for item in selected],
            y = [float_value(item, :validation_matching) for item in selected],
            mode = "lines", line = attr(color = method == "go" ? rgba(GO_COLOR, 0.16) : rgba(GR_COLOR, 0.22), width = 0.8),
            hoverinfo = "skip", showlegend = false, legend = legend_id,
        ); row, col)
    end
    for method in ("go", "gr")
        add_attainment_band!(plot_handle, data, method, row, col; showlegend, legend_id)
        selected = sort([item for item in data.fronts if string_value(item, :front_scope) == "global_method" && string_value(item, :method) == method]; by = item -> int_value(item, :active_groups))
        color = method == "go" ? GO_COLOR : GR_COLOR
        add_trace!(plot_handle, scatter(
            x = [int_value(item, :active_groups) for item in selected],
            y = [float_value(item, :validation_matching) for item in selected],
            mode = "lines+markers", name = "$(uppercase(method)) pooled front",
            line = attr(color = color, width = 3), marker = attr(color = color, size = 7),
            legendgroup = "$(method)_pooled", showlegend = showlegend, legend = legend_id,
        ); row, col)
    end
    candidate_styles = Dict(
        "C_match" => (symbol = "star", color = THIRD_COLOR, size = 14),
        "C_sparse" => (symbol = "diamond-open", color = NEUTRAL_COLOR, size = 12),
    )
    for role in ("C_match", "C_sparse")
        haskey(data.candidates, role) || continue
        candidate = data.candidates[role]
        style = candidate_styles[role]
        add_trace!(plot_handle, scatter(
            x = [Int(candidate[:active_groups])], y = [Float64(candidate[:validation_matching])],
            mode = "markers", name = role, showlegend = showlegend,
            marker = attr(symbol = style.symbol, color = style.color, size = style.size, line = attr(color = "white", width = 1.2)),
            legendgroup = role, legend = legend_id,
        ); row, col)
    end
end

function add_response_panel!(plot_handle, data, response, row, col; showlegend, legend_id = "legend", legend_labels = nothing)
    qualified_groups = Int[item.active_groups for item in response.rows if item.reached]
    maximum_group = isempty(qualified_groups) ? 1 : maximum(qualified_groups)
    missing_level = maximum_group + max(2, ceil(Int, 0.15 * maximum_group))
    has_missing = any(!item.reached for item in response.rows)
    for replicate in P6_REPLICATES
        selected = sort(filter(item -> item.replicate == replicate, response.rows); by = item -> item.strength)
        trend = only(filter(item -> item.replicate == replicate, response.trends))
        rho_text = isfinite(trend.spearman_rho) ? @sprintf("%.3f", trend.spearman_rho) : "NA"
        label = isnothing(legend_labels) ? "Replicate $replicate: ρ=$rho_text (n=$(trend.qualified_strengths))" : legend_labels[replicate]
        add_trace!(plot_handle, scatter(
            x = [item.strength for item in selected],
            y = [item.reached ? Float64(item.active_groups) : NaN for item in selected],
            mode = "lines+markers", connectgaps = false, name = label,
            line = attr(color = REPLICATE_COLORS[replicate], width = 2),
            marker = attr(color = REPLICATE_COLORS[replicate], size = replicate == 1 ? 15 : 8, symbol = ("circle", "square", "diamond")[replicate]),
            legendgroup = "replicate_$replicate", showlegend = showlegend, legend = legend_id,
        ); row, col)
        missing_strengths = [item.strength for item in selected if !item.reached]
        isempty(missing_strengths) || add_trace!(plot_handle, scatter(
            x = missing_strengths, y = fill(missing_level, length(missing_strengths)),
            mode = "markers", name = "Threshold not reached", legendgroup = "not_reached",
            showlegend = showlegend && replicate == 1, legend = legend_id,
            marker = attr(color = NEUTRAL_COLOR, size = 9, symbol = "x"),
        ); row, col)
    end
    return (; maximum_group, missing_level, has_missing)
end

function pareto_y_range(data)
    losses = float_value.(data.fronts, Ref(:validation_matching))
    return [log10(minimum(losses)) - 0.1, log10(max(maximum(losses), 0.01)) + 0.1]
end

function go_evaluations(data, strength_index)
    selected = [item for item in data.checkpoints if
        string_value(item, :method) == "go" &&
        int_value(item, :strength_index) == strength_index &&
        isfinite(float_value(item, :validation_matching)) &&
        float_value(item, :validation_matching) > 0]
    isempty(selected) && error("$(data.protocol): no finite GO evaluations for strength index $strength_index.")
    Set(int_value(item, :replicate) for item in selected) == Set(P6_REPLICATES) ||
        error("$(data.protocol): strength index $strength_index does not contain all three replicates.")
    return selected
end

function add_all_evaluations_panel!(plot_handle, data, row, col; showlegend)
    for strength_index in eachindex(P6_STRENGTHS[data.protocol])
        selected = go_evaluations(data, strength_index)
        label = @sprintf(
            "GO strength F/V %.4g / %.4g",
            P6_STRENGTHS[:fixed][strength_index],
            P6_STRENGTHS[:varying][strength_index],
        )
        add_trace!(plot_handle, scattergl(
            x = [int_value(item, :active_groups) for item in selected],
            y = [float_value(item, :validation_matching) for item in selected],
            mode = "markers", name = label,
            marker = attr(color = EVALUATION_STRENGTH_COLORS[strength_index], size = 5, opacity = 0.42),
            customdata = hcat(
                [int_value(item, :replicate) for item in selected],
                [int_value(item, :update) for item in selected],
            ),
            hovertemplate = "active groups=%{x}<br>validation MSE=%{y:.5g}<br>replicate=%{customdata[0]}<br>update=%{customdata[1]}<extra></extra>",
            legendgroup = "evaluation_strength_$strength_index", showlegend = showlegend,
        ); row, col)
    end

    pooled_front = sort([
        item for item in data.fronts if
        string_value(item, :front_scope) == "global_method" &&
        string_value(item, :method) == "go"
    ]; by = item -> int_value(item, :active_groups))
    isempty(pooled_front) && error("$(data.protocol): pooled GO Pareto front is missing.")
    add_trace!(plot_handle, scatter(
        x = [int_value(item, :active_groups) for item in pooled_front],
        y = [float_value(item, :validation_matching) for item in pooled_front],
        mode = "lines", name = "Pooled GO Pareto front",
        line = attr(color = NEUTRAL_COLOR, width = 2.5),
        legendgroup = "all_evaluations_pooled_front", showlegend = showlegend,
    ); row, col)
end

function all_evaluations_y_range(data)
    losses = Float64[]
    for strength_index in eachindex(P6_STRENGTHS[data.protocol])
        append!(losses, float_value.(go_evaluations(data, strength_index), Ref(:validation_matching)))
    end
    return [log10(minimum(losses)) - 0.1, log10(maximum(losses)) + 0.1]
end

function make_all_evaluations_pareto_figure(data_by_protocol, output)
    plot_handle = make_subplots(
        rows = 1, cols = 2, horizontal_spacing = 0.10,
        subplot_titles = reshape([
            "A  Fixed IC: all GO evaluations",
            "B  Varying IC: all GO evaluations",
        ], :, 1),
    )
    add_all_evaluations_panel!(plot_handle, data_by_protocol[:fixed], 1, 1; showlegend = true)
    add_all_evaluations_panel!(plot_handle, data_by_protocol[:varying], 1, 2; showlegend = false)

    layout = common_layout(width = 1400, height = 650, title = "Package 6: pooled evaluation landscape and Pareto front")
    relayout!(plot_handle, merge(layout.fields, Dict{Symbol, Any}(
        :xaxis => preserved_subplot_axis(plot_handle, :xaxis, paper_axis("Active SC groups"; range = [0, 96])),
        :yaxis => preserved_subplot_axis(plot_handle, :yaxis, paper_axis("Validation MSE"; log = true, range = all_evaluations_y_range(data_by_protocol[:fixed]))),
        :xaxis2 => preserved_subplot_axis(plot_handle, :xaxis2, paper_axis("Active SC groups"; range = [0, 96])),
        :yaxis2 => preserved_subplot_axis(plot_handle, :yaxis2, paper_axis("Validation MSE"; log = true, range = all_evaluations_y_range(data_by_protocol[:varying]))),
        :legend => row_legend(-0.16),
        :margin => attr(l = 85, r = 35, t = 105, b = 125),
    )))
    PlotlyJS.savefig(plot_handle, output; width = 1400, height = 650)
    return output
end

function make_main_figure(data_by_protocol, metrics, output)
    plot_handle = make_subplots(
        rows = 2, cols = 2,
        horizontal_spacing = 0.10, vertical_spacing = 0.23,
        subplot_titles = reshape([
            "A  Fixed IC: Pareto attainment", "B  Varying IC: Pareto attainment",
            "C  Fixed IC: strength-sparsity response", "D  Varying IC: strength-sparsity response",
        ], :, 1),
    )
    add_pareto_panel!(plot_handle, data_by_protocol[:fixed], 1, 1; showlegend = true, legend_id = "legend")
    add_pareto_panel!(plot_handle, data_by_protocol[:varying], 1, 2; showlegend = false, legend_id = "legend")
    response_legend_labels = Dict(replicate => begin
        fixed = only(filter(item -> item.replicate == replicate, metrics.responses[:fixed].trends))
        varying = only(filter(item -> item.replicate == replicate, metrics.responses[:varying].trends))
        @sprintf(
            "Replicate %d: ρ_fixed=%.3f (n=%d), ρ_varying=%.3f (n=%d)",
            replicate, fixed.spearman_rho, fixed.qualified_strengths,
            varying.spearman_rho, varying.qualified_strengths,
        )
    end for replicate in P6_REPLICATES)
    fixed_response = add_response_panel!(
        plot_handle, data_by_protocol[:fixed], metrics.responses[:fixed], 2, 1;
        showlegend = true, legend_id = "legend2", legend_labels = response_legend_labels,
    )
    varying_response = add_response_panel!(
        plot_handle, data_by_protocol[:varying], metrics.responses[:varying], 2, 2;
        showlegend = false, legend_id = "legend2", legend_labels = response_legend_labels,
    )

    fixed_ticks = collect(0:2:fixed_response.maximum_group)
    fixed_ticktext = string.(fixed_ticks)
    if fixed_response.has_missing
        push!(fixed_ticks, fixed_response.missing_level)
        push!(fixed_ticktext, "NR")
    end
    fixed_top = fixed_response.has_missing ? fixed_response.missing_level + 0.6 : fixed_response.maximum_group + 1
    varying_top = varying_response.has_missing ? varying_response.missing_level + 0.5 : varying_response.maximum_group + 1
    layout = common_layout(width = 1400, height = 1120, title = "Package 6: sensitivity, reproducibility, and Pareto performance")
    relayout!(plot_handle, merge(layout.fields, Dict{Symbol, Any}(
        :xaxis => preserved_subplot_axis(plot_handle, :xaxis, paper_axis("Active SC groups")),
        :yaxis => preserved_subplot_axis(plot_handle, :yaxis, paper_axis("Validation MSE"; log = true, range = pareto_y_range(data_by_protocol[:fixed]))),
        :xaxis2 => preserved_subplot_axis(plot_handle, :xaxis2, paper_axis("Active SC groups")),
        :yaxis2 => preserved_subplot_axis(plot_handle, :yaxis2, paper_axis("Validation MSE"; log = true, range = pareto_y_range(data_by_protocol[:varying]))),
        :xaxis3 => preserved_subplot_axis(plot_handle, :xaxis3, paper_axis("GO strength"; log = true, tickmode = "array", tickvals = collect(P6_STRENGTHS[:fixed]), ticktext = string.(P6_STRENGTHS[:fixed]))),
        :yaxis3 => preserved_subplot_axis(plot_handle, :yaxis3, paper_axis("Active groups (MSE <= $(QUALITY_THRESHOLDS[:fixed]))"; range = [0, fixed_top], tickmode = "array", tickvals = fixed_ticks, ticktext = fixed_ticktext)),
        :xaxis4 => preserved_subplot_axis(plot_handle, :xaxis4, paper_axis("GO strength"; log = true, tickmode = "array", tickvals = collect(P6_STRENGTHS[:varying]), ticktext = string.(P6_STRENGTHS[:varying]))),
        :yaxis4 => preserved_subplot_axis(plot_handle, :yaxis4, paper_axis("Active groups (MSE <= $(QUALITY_THRESHOLDS[:varying]))"; range = [0, varying_top])),
        :legend => row_legend(0.505),
        :legend2 => row_legend(-0.085),
    )))
    PlotlyJS.savefig(plot_handle, output; width = 1400, height = 1120)
    return output
end

function role_rows(data, role)
    return filter(row -> string_value(row, :role) == role, data.test_episodes)
end

function make_terminal_figure(data_by_protocol, output)
    plot_handle = make_subplots(
        rows = 1, cols = 2, horizontal_spacing = 0.11,
        subplot_titles = reshape(["A  Fixed IC: test trajectory", "B  Varying IC: paired test episodes"], :, 1),
    )
    fixed = data_by_protocol[:fixed]
    for role in CONTROLLER_ORDER
        selected = sort(role_rows(fixed, role); by = row -> int_value(row, :step))
        isempty(selected) && continue
        add_trace!(plot_handle, scatter(
            x = [int_value(row, :step) for row in selected],
            y = [float_value(row, :global_nusselt) for row in selected],
            mode = "lines", name = CONTROLLER_NAMES[role], legendgroup = role,
            line = attr(color = CONTROLLER_COLORS[role], width = role == "expert" ? 2.5 : 2.0),
            showlegend = true,
        ); row = 1, col = 1)
    end

    varying = data_by_protocol[:varying]
    roles = [role for role in CONTROLLER_ORDER if !isempty(role_rows(varying, role))]
    cases = sort(unique(string_value(row, :case) for row in varying.test_episodes))
    case_values = Dict{Tuple{String, String}, Float64}()
    for case in cases, role in roles
        selected = [row for row in varying.test_episodes if string_value(row, :case) == case && string_value(row, :role) == role]
        isempty(selected) || (case_values[(case, role)] = mean(float_value(row, :global_nusselt) for row in selected))
    end
    display_roles = [CONTROLLER_NAMES[role] for role in roles]
    for case in cases
        all(haskey(case_values, (case, role)) for role in roles) || continue
        add_trace!(plot_handle, scatter(
            x = display_roles, y = [case_values[(case, role)] for role in roles],
            mode = "lines+markers", showlegend = false, hovertemplate = "$case<br>%{x}: Nu=%{y:.4f}<extra></extra>",
            line = attr(color = rgba(NEUTRAL_COLOR, 0.28), width = 1),
            marker = attr(color = rgba(NEUTRAL_COLOR, 0.45), size = 5),
        ); row = 1, col = 2)
    end
    for role in roles
        values = [case_values[(case, role)] for case in cases if haskey(case_values, (case, role))]
        add_trace!(plot_handle, scatter(
            x = fill(CONTROLLER_NAMES[role], length(values)), y = values,
            mode = "markers", showlegend = false,
            marker = attr(color = CONTROLLER_COLORS[role], size = 8, symbol = "circle", line = attr(color = "white", width = 0.8)),
        ); row = 1, col = 2)
        add_trace!(plot_handle, scatter(
            x = [CONTROLLER_NAMES[role]], y = [mean(values)],
            mode = "markers", name = "$(CONTROLLER_NAMES[role]) mean", legendgroup = "$(role)_mean",
            showlegend = false,
            marker = attr(color = CONTROLLER_COLORS[role], size = 14, symbol = "diamond", line = attr(color = "white", width = 1.2)),
        ); row = 1, col = 2)
    end
    layout = common_layout(width = 1350, height = 600, title = "Validation-selected controllers on the terminal test set")
    relayout!(plot_handle, merge(layout.fields, Dict{Symbol, Any}(
        :xaxis => preserved_subplot_axis(plot_handle, :xaxis, paper_axis("Control step")),
        :yaxis => preserved_subplot_axis(plot_handle, :yaxis, paper_axis("Nu")),
        :xaxis2 => preserved_subplot_axis(plot_handle, :xaxis2, attr(title = attr(text = "Controller", standoff = 10), showline = true, mirror = true, linecolor = "#3A3A3A", ticks = "outside", type = "category")),
        :yaxis2 => preserved_subplot_axis(plot_handle, :yaxis2, paper_axis("Mean episode Nu")),
    )))
    PlotlyJS.savefig(plot_handle, output; width = 1350, height = 600)
    return output
end

function add_hitting_panel!(plot_handle, data, row, col; showlegend, legend_id = "legend")
    for (strength_index, strength) in enumerate(P6_STRENGTHS[data.protocol])
        values = Float64[]
        for target in HITTING_TARGETS
            matching = [item for item in data.hitting if
                string_value(item, :method) == "go" &&
                int_value(item, :strength_index) == strength_index &&
                int_value(item, :target_groups) == target]
            length(matching) == 1 || error("Missing GO hitting summary for $(data.protocol), s$strength_index, B=$target.")
            value = optional_float(only(matching), :median_first_update)
            push!(values, value === missing ? NaN : value)
        end
        add_trace!(plot_handle, scatter(
            x = collect(HITTING_TARGETS), y = values, mode = "lines+markers",
            name = @sprintf("GO F/V %.4g / %.4g", P6_STRENGTHS[:fixed][strength_index], P6_STRENGTHS[:varying][strength_index]), legendgroup = "strength_$strength_index",
            line = attr(color = STRENGTH_COLORS[strength_index], width = 2),
            marker = attr(color = STRENGTH_COLORS[strength_index], size = 6), showlegend = showlegend,
            legend = legend_id,
        ); row, col)
    end
    gr_values = Float64[]
    for target in HITTING_TARGETS
        matching = [item for item in data.hitting if string_value(item, :method) == "gr" && int_value(item, :target_groups) == target]
        length(matching) == 1 || error("Missing GR hitting summary for $(data.protocol), B=$target.")
        value = optional_float(only(matching), :median_first_update)
        push!(gr_values, value === missing ? NaN : value)
    end
    add_trace!(plot_handle, scatter(
        x = collect(HITTING_TARGETS), y = gr_values, mode = "lines+markers",
        name = "GR reference", legendgroup = "gr_reference",
        line = attr(color = NEUTRAL_COLOR, width = 2.4, dash = "dash"),
        marker = attr(color = NEUTRAL_COLOR, size = 7), showlegend = showlegend,
        legend = legend_id,
    ); row, col)
end

function reset_rate(row, reset_type)
    key = reset_type === :group ? :group_reset_rate_per_1000 :
          reset_type === :mse ? :mse_reset_rate_per_1000 : :joint_reset_rate_per_1000
    return float_value(row, key)
end

function add_reset_panel!(plot_handle, data, row, col; showlegend, legend_id = "legend")
    offsets = (-0.10, 0.0, 0.10)
    for reset_type in (:group, :mse, :joint)
        color = RESET_COLORS[reset_type]
        medians = Float64[]
        for strength_index in 1:5
            selected = sort([item for item in data.resets if string_value(item, :method) == "go" && int_value(item, :strength_index) == strength_index]; by = item -> int_value(item, :replicate))
            length(selected) == 3 || error("Expected three reset summaries for $(data.protocol), s$strength_index.")
            values = [reset_rate(item, reset_type) for item in selected]
            append_x = [strength_index + offsets[index] for index in eachindex(values)]
            add_trace!(plot_handle, scatter(
                x = append_x, y = values, mode = "markers", showlegend = false, legend = legend_id,
                marker = attr(color = rgba(color, 0.55), size = 6, symbol = ("circle", "square", "diamond")),
                hovertemplate = "Seed %{customdata}<br>rate=%{y:.3f}<extra></extra>", customdata = collect(1:3),
            ); row, col)
            push!(medians, median(values))
        end
        add_trace!(plot_handle, scatter(
            x = collect(1:5), y = medians, mode = "lines+markers",
            name = RESET_LABELS[reset_type], legendgroup = "reset_$reset_type",
            line = attr(color = color, width = 2.2), marker = attr(color = color, size = 8), showlegend = showlegend,
            legend = legend_id,
        ); row, col)
        gr = sort([item for item in data.resets if string_value(item, :method) == "gr"]; by = item -> int_value(item, :replicate))
        gr_values = [reset_rate(item, reset_type) for item in gr]
        add_trace!(plot_handle, scatter(
            x = [6 + offsets[index] for index in eachindex(gr_values)], y = gr_values,
            mode = "markers", showlegend = false, legend = legend_id,
            marker = attr(color = rgba(color, 0.55), size = 6, symbol = ("circle", "square", "diamond")),
        ); row, col)
        add_trace!(plot_handle, scatter(
            x = [6.0], y = [median(gr_values)], mode = "markers", showlegend = false, legend = legend_id,
            marker = attr(color = color, size = 11, symbol = "diamond-open", line = attr(color = color, width = 2)),
        ); row, col)
    end
end

function step_value(rows, update)
    selected = filter(item -> int_value(item, :update) <= update, rows)
    isempty(selected) && return float_value(first(sort(rows; by = item -> int_value(item, :update))), :coverage)
    return float_value(last(sort(selected; by = item -> int_value(item, :update))), :coverage)
end

function archive_series(data, method, strength_index, grid)
    matching = [item for item in data.archive if string_value(item, :method) == method && int_value(item, :strength_index) == strength_index]
    run_ids = sort(unique(string_value(item, :run_id) for item in matching))
    length(run_ids) == 3 || error("Expected three archive runs for $(data.protocol), $method s$strength_index.")
    budget = P6_UPDATES[data.protocol]
    matrix = zeros(Float64, length(run_ids), length(grid))
    for (run_index, run_id) in enumerate(run_ids)
        rows = [item for item in matching if string_value(item, :run_id) == run_id]
        for (grid_index, progress) in enumerate(grid)
            matrix[run_index, grid_index] = step_value(rows, round(Int, progress * budget))
        end
    end
    return (;
        low = vec(minimum(matrix; dims = 1)),
        median = [median(view(matrix, :, index)) for index in axes(matrix, 2)],
        high = vec(maximum(matrix; dims = 1)),
    )
end

function add_archive_panel!(plot_handle, data, row, col; showlegend, legend_id = "legend")
    grid = collect(range(0.0, 1.0; length = 51))
    specifications = [("go", index, @sprintf("GO F/V %.4g / %.4g", P6_STRENGTHS[:fixed][index], P6_STRENGTHS[:varying][index]), STRENGTH_COLORS[index], "solid") for index in 1:5]
    push!(specifications, ("gr", 0, "GR reference", NEUTRAL_COLOR, "dash"))
    for (method, strength_index, label, color, dash) in specifications
        series = archive_series(data, method, strength_index, grid)
        add_trace!(plot_handle, scatter(
            x = grid, y = series.low, mode = "lines", line = attr(color = rgba(color, 0.20), width = 0.5),
            hoverinfo = "skip", showlegend = false, legendgroup = "archive_$(method)_$strength_index", legend = legend_id,
        ); row, col)
        add_trace!(plot_handle, scatter(
            x = grid, y = series.high, mode = "lines", line = attr(color = rgba(color, 0.20), width = 0.5),
            fill = "tonexty", fillcolor = rgba(color, 0.10), hoverinfo = "skip",
            showlegend = false, legendgroup = "archive_$(method)_$strength_index", legend = legend_id,
        ); row, col)
        add_trace!(plot_handle, scatter(
            x = grid, y = series.median, mode = "lines", name = label,
            line = attr(color = color, width = method == "gr" ? 2.5 : 2.0, dash = dash),
            showlegend = showlegend, legendgroup = "archive_$(method)_$strength_index", legend = legend_id,
        ); row, col)
    end
end

function make_supplement_figure(data_by_protocol, output)
    plot_handle = make_subplots(
        rows = 3, cols = 2, horizontal_spacing = 0.10, vertical_spacing = 0.15,
        subplot_titles = reshape([
            "A  Fixed IC: first hitting times", "B  Varying IC: first hitting times",
            "C  Fixed IC: reset rates", "D  Varying IC: reset rates",
            "E  Fixed IC: archive convergence", "F  Varying IC: archive convergence",
        ], :, 1),
    )
    add_hitting_panel!(plot_handle, data_by_protocol[:fixed], 1, 1; showlegend = true, legend_id = "legend")
    add_hitting_panel!(plot_handle, data_by_protocol[:varying], 1, 2; showlegend = false, legend_id = "legend")
    add_reset_panel!(plot_handle, data_by_protocol[:fixed], 2, 1; showlegend = true, legend_id = "legend2")
    add_reset_panel!(plot_handle, data_by_protocol[:varying], 2, 2; showlegend = false, legend_id = "legend2")
    add_archive_panel!(plot_handle, data_by_protocol[:fixed], 3, 1; showlegend = true, legend_id = "legend3")
    add_archive_panel!(plot_handle, data_by_protocol[:varying], 3, 2; showlegend = false, legend_id = "legend3")

    fixed_strength_ticktext = [string(value) for value in P6_STRENGTHS[:fixed]]
    varying_strength_ticktext = [string(value) for value in P6_STRENGTHS[:varying]]
    push!(fixed_strength_ticktext, "GR ref")
    push!(varying_strength_ticktext, "GR ref")
    layout = common_layout(width = 1450, height = 1750, title = "Package 6 supplementary stability diagnostics")
    relayout!(plot_handle, merge(layout.fields, Dict{Symbol, Any}(
        :xaxis => preserved_subplot_axis(plot_handle, :xaxis, paper_axis("Target active SC groups"; reversed = true, tickmode = "array", tickvals = collect(HITTING_TARGETS), ticktext = string.(HITTING_TARGETS))),
        :yaxis => preserved_subplot_axis(plot_handle, :yaxis, paper_axis("Median first update")),
        :xaxis2 => preserved_subplot_axis(plot_handle, :xaxis2, paper_axis("Target active SC groups"; reversed = true, tickmode = "array", tickvals = collect(HITTING_TARGETS), ticktext = string.(HITTING_TARGETS))),
        :yaxis2 => preserved_subplot_axis(plot_handle, :yaxis2, paper_axis("Median first update")),
        :xaxis3 => preserved_subplot_axis(plot_handle, :xaxis3, paper_axis("GO strength / GR reference"; tickmode = "array", tickvals = collect(1:6), ticktext = fixed_strength_ticktext, range = [0.6, 6.4])),
        :yaxis3 => preserved_subplot_axis(plot_handle, :yaxis3, paper_axis("Events per 1,000 updates")),
        :xaxis4 => preserved_subplot_axis(plot_handle, :xaxis4, paper_axis("GO strength / GR reference"; tickmode = "array", tickvals = collect(1:6), ticktext = varying_strength_ticktext, range = [0.6, 6.4])),
        :yaxis4 => preserved_subplot_axis(plot_handle, :yaxis4, paper_axis("Events per 1,000 updates")),
        :xaxis5 => preserved_subplot_axis(plot_handle, :xaxis5, paper_axis("Normalized training progress"; range = [0, 1])),
        :yaxis5 => preserved_subplot_axis(plot_handle, :yaxis5, paper_axis("Final-front envelope coverage"; range = [0, 1.02])),
        :xaxis6 => preserved_subplot_axis(plot_handle, :xaxis6, paper_axis("Normalized training progress"; range = [0, 1])),
        :yaxis6 => preserved_subplot_axis(plot_handle, :yaxis6, paper_axis("Final-front envelope coverage"; range = [0, 1.02])),
        :legend => row_legend(0.70),
        :legend2 => row_legend(0.315),
        :legend3 => row_legend(-0.10),
    )))
    PlotlyJS.savefig(plot_handle, output; width = 1450, height = 1750)
    return output
end

function finite_text(value; digits = 4)
    value === missing && return "NA"
    isfinite(value) || return "not reached"
    return @sprintf("%.*g", digits, value)
end

function role_metric(metrics, protocol, role)
    selected = filter(row -> row.protocol === protocol && row.role == role, metrics.terminal)
    return isempty(selected) ? nothing : only(selected)
end

function candidate_metric(data, role)
    haskey(data.candidates, role) || return nothing
    candidate = data.candidates[role]
    return (groups = Int(candidate[:active_groups]), mse = Float64(candidate[:validation_matching]))
end

function summary_table_rows(data_by_protocol, metrics)
    rows = NamedTuple[]
    for protocol in PROTOCOLS
        retention = only(filter(row -> row.protocol === protocol, metrics.retention))
        match = candidate_metric(data_by_protocol[protocol], "C_match")
        sparse = candidate_metric(data_by_protocol[protocol], "C_sparse")
        expert_test = role_metric(metrics, protocol, "expert")
        match_test = role_metric(metrics, protocol, "C_match")
        sparse_test = role_metric(metrics, protocol, "C_sparse")
        push!(rows, (;
            protocol = PROTOCOL_NAMES[protocol],
            go_combined_retention = "$(retention.go_retained)/$(retention.go_front_points)",
            gr_combined_retention = "$(retention.gr_retained)/$(retention.gr_front_points)",
            c_match_groups = match.groups,
            c_match_validation_mse = match.mse,
            c_sparse_groups = isnothing(sparse) ? missing : sparse.groups,
            c_sparse_validation_mse = isnothing(sparse) ? missing : sparse.mse,
            expert_test_mean_nu = expert_test.mean_nu,
            c_match_test_mean_nu = match_test.mean_nu,
            c_sparse_test_mean_nu = isnothing(sparse_test) ? missing : sparse_test.mean_nu,
        ))
    end
    return rows
end

function write_summary_table(output_dir, rows)
    csv_path = write_csv(joinpath(output_dir, "table_1_summary.csv"), rows)
    markdown_path = joinpath(output_dir, "table_1_summary.md")
    open(markdown_path, "w") do io
        println(io, "# Package 6 summary table\n")
        println(io, "| Protocol | GO retained | GR retained | C_match (groups, validation MSE) | C_sparse (groups, validation MSE) | Expert test mean Nu | C_match test mean Nu | C_sparse test mean Nu |")
        println(io, "|---|---:|---:|---:|---:|---:|---:|---:|")
        for row in rows
            match = "$(row.c_match_groups), $(@sprintf("%.3e", row.c_match_validation_mse))"
            sparse = row.c_sparse_groups === missing ? "NA" : "$(row.c_sparse_groups), $(@sprintf("%.3e", row.c_sparse_validation_mse))"
            sparse_nu = row.c_sparse_test_mean_nu === missing ? "NA" : @sprintf("%.5f", row.c_sparse_test_mean_nu)
            @printf(io, "| %s | %s | %s | %s | %s | %.5f | %.5f | %s |\n",
                row.protocol, row.go_combined_retention, row.gr_combined_retention,
                match, sparse, row.expert_test_mean_nu, row.c_match_test_mean_nu, sparse_nu)
        end
        println(io, "\n`Retained` means retained after pooling the GO and GR method fronts into one combined nondominated front. Test mean Nu is computed with `state_Nu` and lower is better.")
    end
    return (; csv_path, markdown_path)
end

function write_metric_csvs(output_dir, metrics)
    write_csv(joinpath(output_dir, "strength_sparsity_response.csv"), reduce(vcat, [metrics.responses[p].rows for p in PROTOCOLS]))
    write_csv(joinpath(output_dir, "strength_spearman.csv"), reduce(vcat, [metrics.responses[p].trends for p in PROTOCOLS]))
    write_csv(joinpath(output_dir, "quality_constrained_hitting_runs.csv"), reduce(vcat, [metrics.quality_hitting[p].run_rows for p in PROTOCOLS]))
    write_csv(joinpath(output_dir, "quality_constrained_hitting_summary.csv"), reduce(vcat, [metrics.quality_hitting[p].summary_rows for p in PROTOCOLS]))
    write_csv(joinpath(output_dir, "attainment_summary.csv"), metrics.attainment)
    write_csv(joinpath(output_dir, "combined_front_retention.csv"), metrics.retention)
    write_csv(joinpath(output_dir, "terminal_test_summary.csv"), metrics.terminal)
    return nothing
end

function write_metrics_report(output_dir, data_by_protocol, metrics)
    path = joinpath(output_dir, "paper_metrics.md")
    open(path, "w") do io
        println(io, "# Package 6 paper metrics\n")
        println(io, "This report is generated deterministically from the completed Package-6 analysis products. Fixed IC uses the quality threshold `MSE <= $(QUALITY_THRESHOLDS[:fixed])`; Varying IC uses `MSE <= $(QUALITY_THRESHOLDS[:varying])`. No training, validation, candidate selection, or rollout is performed by the paper-figure script.\n")

        println(io, "## 1. Empirical attainment across seeds\n")
        println(io, "`1/3`, `2/3`, and `3/3` are the best validation-MSE envelopes attained by at least one, two, or all three paired replicates at group budget `B`. The log spread is `log(L_3/3 / L_1/3)`; smaller finite values mean less seed sensitivity.\n")
        println(io, "| Protocol | Method | B | 1/3 MSE | 2/3 MSE | 3/3 MSE | Log spread |")
        println(io, "|---|---|---:|---:|---:|---:|---:|")
        for row in metrics.attainment
            @printf(io, "| %s | %s | %d | %s | %s | %s | %s |\n",
                PROTOCOL_NAMES[row.protocol], uppercase(row.method), row.target_groups,
                finite_text(row.mse_1_of_3), finite_text(row.mse_2_of_3), finite_text(row.mse_3_of_3), finite_text(row.log_attainment_spread))
        end

        println(io, "\n## 2. Predictable strength-sparsity response\n")
        println(io, "For each strength and paired replicate, the response is the sparsest run-front point satisfying the protocol-specific quality threshold. `NR` means that the run never placed a point below that threshold in its Pareto archive. Spearman rho correlates the ranks of strength and active-group count over qualifying strengths only. `rho = -1` is a perfectly monotone decrease; magnitude, spacing, and MSE are not encoded. All current correlations use the complete five-strength grid.\n")
        println(io, "| Protocol | Replicate | Qualifying strengths | Spearman rho |")
        println(io, "|---|---:|---:|---:|")
        for protocol in PROTOCOLS, row in metrics.responses[protocol].trends
            @printf(io, "| %s | %d | %d/5 | %s |\n", PROTOCOL_NAMES[protocol], row.replicate, row.qualified_strengths, finite_text(row.spearman_rho))
        end
        println(io, "\nExact strength-by-seed values are in [`strength_sparsity_response.csv`](strength_sparsity_response.csv).\n")

        println(io, "## 3. Quality-constrained sparsification speed and reachability\n")
        println(io, "`T_(B,eps)` is the first update with no more than `B` active groups and validation MSE below the protocol threshold. Median normalized time is reported only among successful seeds and must be read together with reachability `k/3`.\n")
        println(io, "| Protocol | Strength | B | Reachability | Median T/Tmax | Successful-seed range |")
        println(io, "|---|---:|---:|---:|---:|---:|")
        for protocol in PROTOCOLS, row in metrics.quality_hitting[protocol].summary_rows
            median_text = finite_text(row.median_normalized_first_update)
            range_text = row.minimum_normalized_first_update === missing ? "NA" : @sprintf("%.3f-%.3f", row.minimum_normalized_first_update, row.maximum_normalized_first_update)
            @printf(io, "| %s | %.4g | %d | %d/%d | %s | %s |\n",
                PROTOCOL_NAMES[protocol], row.strength, row.target_groups, row.reached_seeds, row.seed_count, median_text, range_text)
        end

        println(io, "\n## 4. Retention on the combined GO-GR Pareto front\n")
        println(io, "| Protocol | GO retained | GR retained | Combined-front size |")
        println(io, "|---|---:|---:|---:|")
        for row in metrics.retention
            @printf(io, "| %s | %d/%d | %d/%d | %d |\n", PROTOCOL_NAMES[row.protocol], row.go_retained, row.go_front_points, row.gr_retained, row.gr_front_points, row.combined_front_points)
        end
        println(io, "\nRetention is evaluated only after each method-specific pooled front has been formed. A retained count of all GO points means that none of the GO front points is dominated in the combined front; it does not mean that every individual GO point dominates every GR point.\n")

        println(io, "## 5. Selection-inert terminal test confirmation\n")
        println(io, "Candidates were loaded from the immutable validation-only manifest. Test mean Nu is the mean of the stored per-step `state_Nu` values over the 200-step episodes; lower is better. The test data are not used to change a candidate, strength, or training decision.\n")
        println(io, "| Protocol | Controller | Cases | Mean Nu | Median case Nu | Case range | Mean raw 200-step return |")
        println(io, "|---|---|---:|---:|---:|---:|---:|")
        for row in metrics.terminal
            @printf(io, "| %s | %s | %d | %.6f | %.6f | %.6f-%.6f | %.6f |\n",
                PROTOCOL_NAMES[row.protocol], CONTROLLER_NAMES[row.role], row.cases, row.mean_nu,
                row.median_case_nu, row.minimum_case_nu, row.maximum_case_nu, row.mean_200_step_return)
        end

        println(io, "\n## Supplementary diagnostics\n")
        println(io, "Panels A/B show the existing unconstrained first-hitting time `T_B`: the median is taken among reachable seeds, so a missing line segment means no seed reached that target. Panels C/D show individual replicate reset rates and their medians; GR appears as a separate categorical reference because GO and GR strength magnitudes are not directly comparable. Panels E/F aggregate the existing monotone archive-coverage definition: for each run, it is the fraction of final-front group-count envelopes already reached within 10%. Lines are seed medians and ribbons are seed minima-to-maxima. This is not a hypervolume ratio.\n")

        println(io, "## Figure files\n")
        println(io, "- [`figure_1_main.svg`](figure_1_main.svg): Pareto/attainment and quality-constrained strength response.")
        println(io, "- [`figure_2_terminal_test.svg`](figure_2_terminal_test.svg): Fixed `state_Nu` trajectory and Varying paired test episodes.")
        println(io, "- [`figure_s1_stability_diagnostics.svg`](figure_s1_stability_diagnostics.svg): hitting times, reset rates, and aggregate archive convergence.")
        println(io, "- [`figure_s2_all_evaluations_pareto.svg`](figure_s2_all_evaluations_pareto.svg): all GO evaluation points pooled across replicates, colored by strength, with the pooled Pareto front.")
        println(io, "- [`table_1_summary.md`](table_1_summary.md): compact paper table.")
    end
    return path
end

function sha256_file(path)
    open(path, "r") do io
        return bytes2hex(SHA.sha256(io))
    end
end

function write_provenance(output_dir, data_by_protocol)
    inputs = String[]
    for protocol in PROTOCOLS
        append!(inputs, collect(values(data_by_protocol[protocol].paths)))
    end
    sort!(unique!(inputs))
    path = joinpath(output_dir, "provenance.sha256")
    open(path, "w") do io
        println(io, "# Package 6 paper-output input manifest")
        println(io, "# Script: $(abspath(@__FILE__))")
        println(io, "# Script SHA-256: $(sha256_file(abspath(@__FILE__)))")
        for input in inputs
            relative = relpath(input, dirname(output_dir))
            println(io, "$(sha256_file(input))  $(replace(relative, '\\' => '/'))")
        end
    end
    return path
end

function run_self_tests()
    @assert split_csv_line("a,b,c") == ["a", "b", "c"]
    @assert split_csv_line("a,\"b,c\",\"d\"\"e\"") == ["a", "b,c", "d\"e"]
    @assert spearman_correlation([1, 2, 3], [3, 2, 1]) == -1.0
    records = [
        Dict(:active_groups => 1, :validation_matching => 2.0, :update => 1, :numeric_status => :ok),
        Dict(:active_groups => 2, :validation_matching => 1.0, :update => 2, :numeric_status => :ok),
        Dict(:active_groups => 3, :validation_matching => 3.0, :update => 3, :numeric_status => :ok),
    ]
    @assert length(scientific_front(records)) == 2
    @assert rgba("#277DA1", 0.5) == "rgba(39,125,161,0.5)"
    @assert length(EVALUATION_STRENGTH_COLORS) == 5
    @assert last(EVALUATION_STRENGTH_COLORS) == GR_COLOR
    println("Package-6 paper figure self-tests passed.")
    return nothing
end

function main(arguments = ARGS)
    options = parse_arguments(arguments)
    isnothing(options) && return nothing
    if options.self_test
        run_self_tests()
        return nothing
    end

    data_by_protocol = Dict(protocol => load_protocol(options.results_dir, protocol) for protocol in PROTOCOLS)
    foreach(validate_loaded_data, values(data_by_protocol))
    metrics = calculate_metrics(data_by_protocol)

    if options.check_only
        for protocol in PROTOCOLS
            response = metrics.responses[protocol]
            retention = only(filter(row -> row.protocol === protocol, metrics.retention))
            println("$(PROTOCOL_NAMES[protocol]): inputs valid; qualifying strength points = $(count(row -> row.reached, response.rows))/15; combined retention GO $(retention.go_retained)/$(retention.go_front_points), GR $(retention.gr_retained)/$(retention.gr_front_points).")
        end
        return nothing
    end

    mkpath(options.output_dir)
    write_metric_csvs(options.output_dir, metrics)
    table_rows = summary_table_rows(data_by_protocol, metrics)
    table_paths = write_summary_table(options.output_dir, table_rows)
    report_path = write_metrics_report(options.output_dir, data_by_protocol, metrics)
    provenance_path = write_provenance(options.output_dir, data_by_protocol)

    main_figure = make_main_figure(data_by_protocol, metrics, joinpath(options.output_dir, "figure_1_main.svg"))
    terminal_figure = make_terminal_figure(data_by_protocol, joinpath(options.output_dir, "figure_2_terminal_test.svg"))
    supplement_figure = make_supplement_figure(data_by_protocol, joinpath(options.output_dir, "figure_s1_stability_diagnostics.svg"))
    evaluation_figure = make_all_evaluations_pareto_figure(data_by_protocol, joinpath(options.output_dir, "figure_s2_all_evaluations_pareto.svg"))

    println("Package-6 paper outputs written to $(options.output_dir):")
    for path in (main_figure, terminal_figure, supplement_figure, evaluation_figure, table_paths.markdown_path, report_path, provenance_path)
        println("  $(path)")
    end
    return nothing
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
