using Dates
using Printf

# ---------------------------------------------------------------------------
# Fixed-IC Package-6 technical pilot configuration
# ---------------------------------------------------------------------------

const P6_FIXED_PILOT_SEED = 600_601
const P6_FIXED_PILOT_REGULARIZATION_STRENGTH = 0.09
const P6_FIXED_PILOT_REGULARIZED_UPDATES = 6_000
const P6_FIXED_PILOT_BATCH_SIZE = 20
const P6_FIXED_PILOT_PROXIMAL_INTERVAL = 1
const P6_FIXED_PILOT_EVALUATION_START = 2_000
const P6_FIXED_PILOT_EVALUATION_INTERVAL = 5
const P6_FIXED_PILOT_RESUME_INTERVAL = 100
const P6_FIXED_PILOT_GARBAGE_COLLECTION_INTERVAL = 5

const P6_DIRECTORY = @__DIR__
const REVISION_DIRECTORY = normpath(joinpath(P6_DIRECTORY, ".."))
const DISTILLATION_DIRECTORY = joinpath(
    REVISION_DIRECTORY,
    "Expert_Apprentice_Distillation",
)
const P6_FIXED_EXPERT_PATH = joinpath(
    DISTILLATION_DIRECTORY,
    "experts",
    "fixed",
    "agent.jld2",
)
const P6_DISTILLATION_WORKER_DIRECTORY = joinpath(
    DISTILLATION_DIRECTORY,
    "worker_results",
)
const P6_FIXED_PILOT_RESULTS_ROOT = joinpath(P6_DIRECTORY, "results", "fixed_pilot")

function strength_tag(value::Real)
    return replace(@sprintf("%.8g", Float64(value)), "." => "p", "-" => "m")
end

const P6_FIXED_PILOT_RUN_ID =
    "fixed_go_pilot_strength_$(strength_tag(P6_FIXED_PILOT_REGULARIZATION_STRENGTH))_" *
    "seed_$(P6_FIXED_PILOT_SEED)_updates_$(P6_FIXED_PILOT_REGULARIZED_UPDATES)_" *
    "eval_start_$(P6_FIXED_PILOT_EVALUATION_START)_" *
    "interval_$(P6_FIXED_PILOT_EVALUATION_INTERVAL)"
const P6_FIXED_PILOT_RUN_DIRECTORY = joinpath(
    P6_FIXED_PILOT_RESULTS_ROOT,
    P6_FIXED_PILOT_RUN_ID,
)

# These variables must be set before Expert_Apprentice.jl includes the Fixed
# Revision MAT run file and the DistillationCorpus loader.
ENV["DISTILLATION_PROTOCOL"] = "fixed"
ENV["REVISION_RUN_SEED"] = string(P6_FIXED_PILOT_SEED)
ENV["DISTILLATION_FIXED_EXPERT_PATH"] = P6_FIXED_EXPERT_PATH
ENV["DISTILLATION_WORKER_DIRECTORY"] = P6_DISTILLATION_WORKER_DIRECTORY
ENV["DISTILLATION_ALLOW_FRESH_EXPERT"] = "false"
ENV["REVISION_RUN_DIRECTORY"] = joinpath(P6_DIRECTORY, "runtime", P6_FIXED_PILOT_RUN_ID)
ENV["DISTILLATION_OUTPUT_DIRECTORY"] = joinpath(
    P6_FIXED_PILOT_RUN_DIRECTORY,
    "apprentice_outputs",
)

include(joinpath(DISTILLATION_DIRECTORY, "Expert_Apprentice.jl"))

function pilot_threshold_specs()
    return [
        HardThresholdSpec(
            :pilot_relative_001,
            :relative_to_max,
            0.01;
            analysis_scope = :pilot_only,
        ),
        HardThresholdSpec(
            :pilot_keep_6_groups,
            :keep_groups,
            6;
            analysis_scope = :pilot_only,
        ),
    ]
end

function assert_fixed_pilot_inputs()
    isfile(P6_FIXED_EXPERT_PATH) || error(
        "Fixed expert checkpoint is missing: $P6_FIXED_EXPERT_PATH",
    )
    coverage = distillation_coverage(:fixed)
    coverage.complete || error(
        "Incomplete Fixed-IC distillation corpus: expected $(coverage.expected), " *
        "found $(coverage.actual).",
    )
    train_dataset = distillation_dataset(:fixed, :train)
    validation_dataset = distillation_dataset(:fixed, :validation)
    test_dataset = distillation_dataset(:fixed, :test)

    (train_dataset === validation_dataset && validation_dataset === test_dataset) || error(
        "Fixed IC must expose the same dataset object as train, validation, and test.",
    )
    Int(train_dataset[:sample_count]) == 200 || error(
        "Fixed pilot expects exactly 200 corpus samples, found $(train_dataset[:sample_count]).",
    )
    length(train_dataset[:episodes]) == 1 || error(
        "Fixed pilot expects exactly one corpus episode.",
    )

    loaded_expert_identifier = string(DISTILLATION_EXPERT_METADATA[:identifier])
    corpus_expert_identifier = string(train_dataset[:expert_identifier])
    loaded_expert_identifier == corpus_expert_identifier || error(
        "Fixed corpus was generated by $corpus_expert_identifier, but the selected expert is " *
        "$loaded_expert_identifier. Regenerate the corpus with the selected checkpoint.",
    )
    return (coverage, train_dataset, validation_dataset, corpus_expert_identifier)
end

function pilot_archive_config(
    training_config::ApprenticeTrainingConfig,
    threshold_specs,
    corpus_expert_identifier,
    train_dataset,
)
    return Dict{Symbol, Any}(
        :experiment => :package6_fixed_technical_pilot,
        :scientific_result => false,
        :protocol => :fixed,
        :method => :go,
        :apprentice_seed => P6_FIXED_PILOT_SEED,
        :batch_order_seed => P6_FIXED_PILOT_SEED + 10_000,
        :regularization_strength => training_config.regularization_strength,
        :regularized_updates => training_config.regularized_updates,
        :post_pruning_finetune_updates => training_config.post_pruning_finetune_updates,
        :batch_size => training_config.batch_size,
        :proximal_interval => training_config.proximal_interval,
        :validation_batch_size => training_config.validation_batch_size,
        :validation_prediction_mode => training_config.validation_prediction_mode,
        :diagnostic_teacher_forced => training_config.diagnostic_teacher_forced,
        :group_rows_by_overlap => true,
        :group_channels => true,
        :expert_identifier => corpus_expert_identifier,
        :expert_path => abspath(P6_FIXED_EXPERT_PATH),
        :corpus_source_files => abspath.(String.(train_dataset[:source_files])),
        :corpus_sample_count => Int(train_dataset[:sample_count]),
        :threshold_specs => [
            (
                id = spec.id,
                mode = spec.mode,
                value = spec.value,
                analysis_scope = spec.analysis_scope,
            )
            for spec in threshold_specs
        ],
    )
end

function print_pilot_front(manager::ParetoArchiveManager)
    println()
    println("Current per-run Pareto front ($(length(manager.front)) candidates):")
    println("  update   threshold                    active inputs   validation MSE")
    println("  ------   ---------------------------  -------------   --------------")
    for candidate in manager.front
        @printf(
            "  %6d   %-27s  %13d   %.8e\n",
            Int(candidate[:update]),
            string(candidate[:threshold_id]),
            Int(candidate[:active_inputs]),
            Float64(candidate[:validation_matching]),
        )
    end

    native_front = filter(
        candidate -> get(candidate, :analysis_scope, nothing) === :package6_native_sensitivity,
        manager.front,
    )
    println("Native Package-6 front candidates: $(length(native_front))")
    println("Archive: $(manager.run_directory)")
    return nothing
end

function save_pilot_summary!(manager::ParetoArchiveManager, result, elapsed_seconds::Real)
    summary_path = joinpath(manager.run_directory, "pilot_summary.jld2")
    pareto_atomic_save(
        summary_path;
        experiment = :package6_fixed_technical_pilot,
        scientific_result = false,
        run_id = manager.run_id,
        completed_at = string(Dates.now()),
        elapsed_seconds = Float64(elapsed_seconds),
        update_count = length(result.losses),
        final_training_loss = isempty(result.losses) ? NaN : last(result.losses),
        regularization_strength = result.regularization_strength,
        evaluation_count = manager.evaluation_count,
        pareto_front = manager.front,
    )
    return summary_path
end

function run_fixed_pilot()
    coverage, train_dataset, validation_dataset, expert_identifier =
        assert_fixed_pilot_inputs()
    threshold_specs = pilot_threshold_specs()
    training_config = ApprenticeTrainingConfig(
        regularized_updates = P6_FIXED_PILOT_REGULARIZED_UPDATES,
        post_pruning_finetune_updates = 0,
        batch_size = P6_FIXED_PILOT_BATCH_SIZE,
        proximal_interval = P6_FIXED_PILOT_PROXIMAL_INTERVAL,
        reweight_interval = 10,
        regularization_strength = P6_FIXED_PILOT_REGULARIZATION_STRENGTH,
        validation_batch_size = 200,
        validation_prediction_mode = :autoregressive,
        diagnostic_teacher_forced = true,
    )
    schedule = CandidateSchedule(
        start_update = P6_FIXED_PILOT_EVALUATION_START,
        evaluation_interval = P6_FIXED_PILOT_EVALUATION_INTERVAL,
        garbage_collection_interval = P6_FIXED_PILOT_GARBAGE_COLLECTION_INTERVAL,
        resume_interval = P6_FIXED_PILOT_RESUME_INTERVAL,
    )
    archive_config = pilot_archive_config(
        training_config,
        threshold_specs,
        expert_identifier,
        train_dataset,
    )
    manager = initialize_pareto_archive(
        P6_FIXED_PILOT_RUN_DIRECTORY;
        run_id = P6_FIXED_PILOT_RUN_ID,
        schedule,
        config = archive_config,
    )

    resume_checkpoint = load_resume_checkpoint(manager)
    if !isnothing(resume_checkpoint) && resume_checkpoint.status === :complete
        println("Fixed pilot is already complete at update $(resume_checkpoint.update).")
        print_pilot_front(manager)
        return manager
    elseif !isnothing(resume_checkpoint) && resume_checkpoint.status === :failed
        failure_message = get(
            resume_checkpoint.resume_state,
            :failure_message,
            "unknown numerical failure",
        )
        error(
            "The previous pilot stopped on a numerical failure at update " *
            "$(resume_checkpoint.update): $failure_message",
        )
    end
    resume = !isnothing(resume_checkpoint)

    println("Package-6 Fixed-IC GO technical pilot")
    println("  run id:                  $P6_FIXED_PILOT_RUN_ID")
    println("  expert:                  $expert_identifier")
    println("  corpus coverage:         $(coverage.actual)")
    println("  apprentice seed:         $P6_FIXED_PILOT_SEED")
    println("  regularization strength: $P6_FIXED_PILOT_REGULARIZATION_STRENGTH")
    println("  updates:                 $P6_FIXED_PILOT_REGULARIZED_UPDATES")
    println("  first evaluation:        $P6_FIXED_PILOT_EVALUATION_START")
    println("  evaluation interval:     $P6_FIXED_PILOT_EVALUATION_INTERVAL")
    println("  resume:                  $resume")
    println("  output:                  $P6_FIXED_PILOT_RUN_DIRECTORY")
    println()

    started_at = time()
    result = train_apprentice!(
        apprentice;
        method = :go,
        train_dataset,
        validation_dataset,
        config = training_config,
        archive_manager = manager,
        threshold_specs,
        group_rows_by_overlap = true,
        group_channels = true,
        training_rng = StableRNG(P6_FIXED_PILOT_SEED + 10_000),
        resume,
    )
    elapsed_seconds = time() - started_at
    summary_path = save_pilot_summary!(manager, result, elapsed_seconds)

    println()
    @printf("Pilot completed in %.2f seconds.\n", elapsed_seconds)
    println("Summary: $summary_path")
    print_pilot_front(manager)
    return manager
end

if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    try
        run_fixed_pilot()
    catch error_value
        Base.display_error(stderr, error_value, catch_backtrace())
        exit(1)
    end
end
