using Dates
using JLD2
using Printf
using SHA

include(joinpath(@__DIR__, "Package6Study.jl"))
using .Package6Study

const P6_DIRECTORY = @__DIR__
const P6_PROJECT_ROOT = normpath(joinpath(P6_DIRECTORY, "..", ".."))
const P6_DISTILLATION_DIRECTORY = joinpath(P6_PROJECT_ROOT, "Revision", "Expert_Apprentice_Distillation")
const P6_DEFAULT_RESULTS_ROOT = joinpath(P6_DIRECTORY, "results", "study")

function worker_usage(io::IO = stdout)
    println(io, """
    Package-6 SC sensitivity worker.

    Usage:
      julia --project=. run_study_worker.jl --protocol fixed|varying \\
        --method go|gr --strength-index N --replicate N [--results-dir PATH]
        [--retry-failed] [--smoke-updates N]

    For GR, --strength-index must be 0. --smoke-updates is test-only and is
    deliberately recorded in the configuration fingerprint.
    """)
end

function parse_worker_arguments(arguments)
    values = Dict{String, Any}(
        "protocol" => nothing,
        "method" => nothing,
        "strength_index" => nothing,
        "replicate" => nothing,
        "results_dir" => P6_DEFAULT_RESULTS_ROOT,
        "retry_failed" => false,
        "smoke_updates" => nothing,
    )
    index = 1
    while index <= length(arguments)
        argument = arguments[index]
        if argument == "--help"
            worker_usage()
            return nothing
        elseif argument == "--retry-failed"
            values["retry_failed"] = true
            index += 1
        elseif startswith(argument, "--")
            index == length(arguments) && error("Missing value after $argument.")
            key = replace(argument[3:end], "-" => "_")
            haskey(values, key) || error("Unknown option '$argument'.")
            values[key] = arguments[index + 1]
            index += 2
        else
            error("Unknown argument '$argument'.")
        end
    end
    for key in ("protocol", "method", "strength_index", "replicate")
        isnothing(values[key]) && error("--$(replace(key, "_" => "-")) is required.")
    end
    protocol = normalize_protocol(values["protocol"])
    method = Symbol(lowercase(string(values["method"])))
    method in (:go, :gr) || error("--method must be go or gr.")
    strength_index = parse(Int, string(values["strength_index"]))
    replicate = parse(Int, string(values["replicate"]))
    job = job_for(protocol, method, strength_index, replicate)
    smoke_updates = isnothing(values["smoke_updates"]) ? nothing : parse(Int, string(values["smoke_updates"]))
    !isnothing(smoke_updates) && smoke_updates < 0 && error("--smoke-updates must be nonnegative.")
    return (
        job,
        results_root = abspath(string(values["results_dir"])),
        retry_failed = Bool(values["retry_failed"]),
        smoke_updates,
    )
end

function configure_worker_environment!(options)
    job = options.job
    directory = run_directory(options.results_root, job)
    expert_path = joinpath(P6_DISTILLATION_DIRECTORY, "experts", string(job.protocol), "agent.jld2")
    ENV["DISTILLATION_PROTOCOL"] = string(job.protocol)
    ENV["DISTILLATION_AUTOLOAD_PROTOCOL"] = string(job.protocol)
    ENV["DISTILLATION_SKIP_AUTOLOAD"] = "false"
    ENV["DISTILLATION_GROUP_CHANNELS"] = "false"
    ENV["REVISION_RUN_SEED"] = string(job.apprentice_seed)
    ENV[job.protocol === :fixed ? "DISTILLATION_FIXED_EXPERT_PATH" : "DISTILLATION_VARYING_EXPERT_PATH"] = expert_path
    ENV["DISTILLATION_WORKER_DIRECTORY"] = joinpath(P6_DISTILLATION_DIRECTORY, "worker_results")
    ENV["DISTILLATION_ALLOW_FRESH_EXPERT"] = "false"
    ENV["REVISION_RUN_DIRECTORY"] = joinpath(directory, "runtime")
    ENV["DISTILLATION_OUTPUT_DIRECTORY"] = joinpath(directory, "apprentice_output")
    return (directory, expert_path)
end

function assert_study_inputs(protocol::Symbol, expert_path::AbstractString)
    isfile(expert_path) || error("Expert checkpoint is missing: $expert_path")
    coverages = Dict(split => distillation_coverage(protocol, split) for split in (:train, :validation, :test))
    for split in (:train, :validation, :test)
        coverage = coverages[split]
        coverage.complete || error(
            "Incomplete $protocol/$split distillation corpus: expected $(coverage.expected), found $(coverage.actual).",
        )
    end
    datasets = Dict(split => distillation_dataset(protocol, split) for split in (:train, :validation, :test))
    identifiers = Set(string(datasets[split][:expert_identifier]) for split in keys(datasets))
    length(identifiers) == 1 || error("$protocol corpus splits were generated by different experts: $identifiers")
    corpus_identifier = only(identifiers)
    loaded_identifier = string(DISTILLATION_EXPERT_METADATA[:identifier])
    corpus_identifier == loaded_identifier || error(
        "$protocol corpus expert $corpus_identifier does not match loaded expert $loaded_identifier.",
    )
    if protocol === :fixed
        datasets[:train] === datasets[:validation] === datasets[:test] || error(
            "Fixed IC must expose one shared train/validation/test dataset object.",
        )
    else
        length(Set(objectid(datasets[split]) for split in keys(datasets))) == 3 || error(
            "Varying IC requires distinct train, validation, and test dataset objects.",
        )
    end
    return (coverages, datasets, corpus_identifier)
end

function write_array_for_hash!(io::IO, values)
    array = Array(values)
    write(io, string(eltype(array)), UInt8(0), string(size(array)), UInt8(0))
    write(io, reinterpret(UInt8, vec(array)))
end

function apprentice_parameter_hash(model)
    io = IOBuffer()
    parameters = Flux.trainables(model)
    write(io, string(length(parameters)), UInt8(0))
    foreach(parameter -> write_array_for_hash!(io, parameter), parameters)
    return bytes2hex(SHA.sha256(take!(io)))
end

function study_archive_config(job, updates, training_config, expert_path, corpus_identifier, datasets, initial_hash; smoke_test)
    return Dict{Symbol, Any}(
        :schema_version => P6_SCHEMA_VERSION,
        :experiment => :package6_sc_go_sensitivity,
        :scientific_scope => smoke_test ? :smoke_test : :package6,
        :protocol => job.protocol,
        :method => job.method,
        :group_rows_by_overlap => true,
        :group_channels => false,
        :grouping => :separate_channels,
        :native_sparsity_only => true,
        :hard_threshold_candidates => false,
        :slim_evaluation_records => true,
        :post_pruning_finetune_updates => 0,
        :result_dependent_stopping => false,
        :replicate => job.replicate,
        :pairing_hash => job.pairing_hash,
        :apprentice_seed => job.apprentice_seed,
        :batch_order_seed => job.batch_seed,
        :strength_index => job.strength_index,
        :go_strength_grid => collect(P6_STRENGTHS),
        :regularization_strength => job.regularization_strength,
        :regression_learning_rate => P6_REGRESSION_LEARNING_RATE,
        :regularized_updates => updates,
        :batch_size => training_config.batch_size,
        :proximal_interval => training_config.proximal_interval,
        :reweight_interval => training_config.reweight_interval,
        :validation_batch_size => training_config.validation_batch_size,
        :validation_prediction_mode => training_config.validation_prediction_mode,
        :diagnostic_teacher_forced => training_config.diagnostic_teacher_forced,
        :evaluation_start => 0,
        :evaluation_interval => P6_EVALUATION_INTERVAL,
        :initial_apprentice_parameter_hash => initial_hash,
        :expert_identifier => corpus_identifier,
        :expert_path => abspath(expert_path),
        :train_source_files => abspath.(String.(datasets[:train][:source_files])),
        :validation_source_files => abspath.(String.(datasets[:validation][:source_files])),
        :test_source_files => abspath.(String.(datasets[:test][:source_files])),
        :train_sample_count => Int(datasets[:train][:sample_count]),
        :validation_sample_count => Int(datasets[:validation][:sample_count]),
        :test_sample_count => Int(datasets[:test][:sample_count]),
        :test_data_used_for_training_or_selection => false,
    )
end

function save_study_summary!(manager, job, result, elapsed_seconds)
    return pareto_atomic_save(
        joinpath(manager.run_directory, "summary.jld2");
        schema_version = P6_SCHEMA_VERSION,
        experiment = :package6_sc_go_sensitivity,
        completed_at = string(Dates.now()),
        run_id = job.id,
        protocol = job.protocol,
        method = job.method,
        replicate = job.replicate,
        regularization_strength = job.regularization_strength,
        elapsed_seconds = Float64(elapsed_seconds),
        update_count = length(result.losses),
        final_training_loss = isempty(result.losses) ? NaN : last(result.losses),
        evaluation_count = manager.evaluation_count,
        pareto_front = manager.front,
        config_fingerprint = manager.config_fingerprint,
    )
end

function validate_complete_run_without_runtime(options, previous)
    job = options.job
    directory = run_directory(options.results_root, job)
    config_path = joinpath(directory, "config.jld2")
    summary_path = joinpath(directory, "summary.jld2")
    resume_path = joinpath(directory, "resume", "latest.jld2")
    all(isfile, (config_path, summary_path, resume_path)) || error(
        "Run $(job.id) is marked complete but is missing config, summary, or resume data.",
    )
    loaded_config = JLD2.load(config_path)
    config = Dict{Symbol, Any}(Symbol(key) => value for (key, value) in loaded_config["config"])
    config_fingerprint = string(loaded_config["config_fingerprint"])
    string(previous[:config_fingerprint]) == config_fingerprint || error("Complete status/config fingerprint mismatch.")
    expected_updates = isnothing(options.smoke_updates) ? job.updates : options.smoke_updates
    checks = (
        Symbol(config[:experiment]) === :package6_sc_go_sensitivity,
        Symbol(config[:protocol]) === job.protocol,
        Symbol(config[:method]) === job.method,
        Int(config[:replicate]) == job.replicate,
        Int(config[:strength_index]) == job.strength_index,
        Float64(config[:regularization_strength]) == job.regularization_strength,
        Int(config[:apprentice_seed]) == job.apprentice_seed,
        Int(config[:batch_order_seed]) == job.batch_seed,
        Int(config[:regularized_updates]) == expected_updates,
        Int(config[:evaluation_interval]) == P6_EVALUATION_INTERVAL,
        Float64(config[:regression_learning_rate]) == P6_REGRESSION_LEARNING_RATE,
        Int(config[:batch_size]) == P6_TRAINING_BATCH_SIZE[job.protocol],
        Int(config[:validation_batch_size]) == P6_VALIDATION_BATCH_SIZE[job.protocol],
        Bool(config[:group_channels]) == false,
        length(string(config[:initial_apprentice_parameter_hash])) == 64,
    )
    all(checks) || error("Complete run $(job.id) does not match the requested configuration.")
    if Bool(get(config, :slim_evaluation_records, false))
        isfile(joinpath(directory, "evaluations.jld2")) || error(
            "Complete compact run $(job.id) is missing evaluations.jld2.",
        )
        shard_directory = joinpath(directory, "evaluations")
        shards = isdir(shard_directory) ? filter(
            name -> startswith(name, "update_") && endswith(name, ".jld2"),
            readdir(shard_directory),
        ) : String[]
        isempty(shards) || error("Complete compact run $(job.id) still contains evaluation shards.")
    end
    summary = JLD2.load(summary_path)
    string(summary["config_fingerprint"]) == config_fingerprint || error("Complete summary/config fingerprint mismatch.")
    JLD2.jldopen(resume_path, "r") do resume
        string(resume["config_fingerprint"]) == config_fingerprint || error("Complete resume/config fingerprint mismatch.")
        Symbol(resume["status"]) === :complete || error("Complete run has a non-complete resume checkpoint.")
        Int(resume["update"]) == expected_updates || error("Complete resume checkpoint has the wrong final update.")
    end
    return directory
end

function run_loaded_study_worker(options, directory, expert_path)
    job = options.job
    Float64(learning_rate) == P6_REGRESSION_LEARNING_RATE || error(
        "Loaded regression learning rate $learning_rate does not match $P6_REGRESSION_LEARNING_RATE.",
    )
    coverages, datasets, corpus_identifier = assert_study_inputs(job.protocol, expert_path)
    initial_apprentice = deepcopy(apprentice)
    initial_hash = apprentice_parameter_hash(initial_apprentice)
    updates = isnothing(options.smoke_updates) ? job.updates : options.smoke_updates
    training_config = ApprenticeTrainingConfig(
        regularized_updates = updates,
        post_pruning_finetune_updates = 0,
        batch_size = P6_TRAINING_BATCH_SIZE[job.protocol],
        proximal_interval = 1,
        reweight_interval = 10,
        regularization_strength = job.regularization_strength,
        validation_batch_size = P6_VALIDATION_BATCH_SIZE[job.protocol],
        validation_prediction_mode = :autoregressive,
        diagnostic_teacher_forced = false,
    )
    schedule = CandidateSchedule(
        start_update = 0,
        evaluation_interval = P6_EVALUATION_INTERVAL,
        garbage_collection_interval = P6_GARBAGE_COLLECTION_INTERVAL,
        resume_interval = P6_RESUME_INTERVAL,
    )
    config = study_archive_config(
        job,
        updates,
        training_config,
        expert_path,
        corpus_identifier,
        datasets,
        initial_hash;
        smoke_test = !isnothing(options.smoke_updates),
    )
    manager = initialize_pareto_archive(directory; run_id = job.id, schedule, config)
    resume_checkpoint = load_resume_checkpoint(manager)
    if !isnothing(resume_checkpoint) && resume_checkpoint.status === :complete
        isfile(joinpath(directory, "summary.jld2")) || error("Complete run is missing summary.jld2.")
        compact_evaluations!(manager)
        write_status!(
            status_path(options.results_root, job);
            state = :complete,
            run_id = job.id,
            config_fingerprint = manager.config_fingerprint,
            update = resume_checkpoint.update,
            initial_apprentice_parameter_hash = initial_hash,
            skipped_complete = true,
        )
        println("Skipping complete run $(job.id).")
        return manager
    elseif !isnothing(resume_checkpoint) && resume_checkpoint.status === :failed && !options.retry_failed
        message = get(resume_checkpoint.resume_state, :failure_message, "unknown failure")
        error("Run $(job.id) is marked failed at update $(resume_checkpoint.update): $message. Use --retry-failed only after repairing the cause.")
    end
    resume = !isnothing(resume_checkpoint) && resume_checkpoint.status in (:running, :failed)
    write_status!(
        status_path(options.results_root, job);
        state = :running,
        run_id = job.id,
        protocol = job.protocol,
        method = job.method,
        replicate = job.replicate,
        strength_index = job.strength_index,
        regularization_strength = job.regularization_strength,
        update = isnothing(resume_checkpoint) ? 0 : resume_checkpoint.update,
        config_fingerprint = manager.config_fingerprint,
        initial_apprentice_parameter_hash = initial_hash,
        resumed = resume,
        started_at = string(Dates.now()),
    )

    println("Package 6 SC worker $(job.id)")
    println("  method/strength: $(job.method) / $(job.regularization_strength)")
    println("  replicate/seeds: $(job.replicate) / $(job.apprentice_seed), $(job.batch_seed)")
    println("  updates: $updates; validation interval: $P6_EVALUATION_INTERVAL")
    println("  corpus coverage: train=$(coverages[:train].actual), validation=$(coverages[:validation].actual), test=$(coverages[:test].actual) (unused)")
    println("  resume: $resume")
    println("  output: $directory")
    started = time()
    result = train_apprentice!(
        deepcopy(initial_apprentice);
        method = job.method,
        train_dataset = datasets[:train],
        validation_dataset = datasets[:validation],
        config = training_config,
        archive_manager = manager,
        threshold_specs = HardThresholdSpec[],
        group_rows_by_overlap = true,
        group_channels = false,
        training_rng = StableRNG(job.batch_seed),
        resume,
    )
    elapsed = time() - started
    summary = save_study_summary!(manager, job, result, elapsed)
    compact_evaluations!(manager)
    write_status!(
        status_path(options.results_root, job);
        state = :complete,
        run_id = job.id,
        protocol = job.protocol,
        method = job.method,
        replicate = job.replicate,
        strength_index = job.strength_index,
        regularization_strength = job.regularization_strength,
        update = updates,
        config_fingerprint = manager.config_fingerprint,
        initial_apprentice_parameter_hash = initial_hash,
        elapsed_seconds = elapsed,
        summary_path = summary,
        completed_at = string(Dates.now()),
    )
    @printf("Completed %s in %.2f seconds.\n", job.id, elapsed)
    return manager
end

function study_worker_main(arguments = ARGS)
    options = parse_worker_arguments(arguments)
    isnothing(options) && return nothing
    state_path = status_path(options.results_root, options.job)
    previous = load_status(state_path)
    if !isnothing(previous) && previous[:state] === :failed && !options.retry_failed
        error("Run $(options.job.id) is explicitly failed. Repair it and restart with --retry-failed.")
    end
    if !isnothing(previous) && previous[:state] === :complete
        try
            directory = validate_complete_run_without_runtime(options, previous)
            println("Skipping identity-checked complete run $(options.job.id): $directory")
            return directory
        catch error_value
            atomic_save(
                joinpath(run_directory(options.results_root, options.job), "failed_restart_attempt.jld2");
                schema_version = P6_SCHEMA_VERSION,
                state = :failed,
                run_id = options.job.id,
                error_type = string(typeof(error_value)),
                error_message = sprint(showerror, error_value),
                backtrace = sprint(Base.show_backtrace, catch_backtrace()),
                failed_at = string(Dates.now()),
            )
            rethrow()
        end
    end
    directory, expert_path = configure_worker_environment!(options)
    try
        include(joinpath(P6_DISTILLATION_DIRECTORY, "Expert_Apprentice.jl"))
        return Base.invokelatest(run_loaded_study_worker, options, directory, expert_path)
    catch error_value
        failure_entries = (
            run_id = options.job.id,
            protocol = options.job.protocol,
            method = options.job.method,
            replicate = options.job.replicate,
            strength_index = options.job.strength_index,
            regularization_strength = options.job.regularization_strength,
            error_type = string(typeof(error_value)),
            error_message = sprint(showerror, error_value),
            backtrace = sprint(Base.show_backtrace, catch_backtrace()),
            failed_at = string(Dates.now()),
        )
        if !isnothing(previous) && previous[:state] === :complete
            # A mismatched restart attempt must never destroy a valid complete
            # status. Preserve it and record the rejected attempt separately.
            atomic_save(
                joinpath(run_directory(options.results_root, options.job), "failed_restart_attempt.jld2");
                schema_version = P6_SCHEMA_VERSION,
                state = :failed,
                failure_entries...,
            )
        else
            write_status!(state_path; state = :failed, failure_entries...)
        end
        rethrow()
    end
end

if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    try
        study_worker_main()
    catch error_value
        Base.display_error(stderr, error_value, catch_backtrace())
        exit(1)
    end
end
